# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSql import QSqlDatabase , QSqlQuery
import os
import datetime

class Ui_Edit(QtWidgets.QWidget):
        signal = QtCore.pyqtSignal(str)
        def setupUi(self, Edit):
                self.edit = Edit
                Edit.setObjectName("Edit")
                Edit.resize(429, 541)
                Edit.setStyleSheet("background-color: rgb(0, 0, 8);\n"
                "color:white;")
                self.horizontalLayout = QtWidgets.QHBoxLayout(Edit)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.frame = QtWidgets.QFrame(Edit)
                self.frame.setMaximumSize(QtCore.QSize(405, 16777215))
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
                self.horizontalLayout_6.setObjectName("horizontalLayout_6")
                self.frame_2 = QtWidgets.QFrame(self.frame)
                self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_2.setObjectName("frame_2")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
                self.verticalLayout.setObjectName("verticalLayout")
                self.frame_3 = QtWidgets.QFrame(self.frame_2)
                self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_3.setObjectName("frame_3")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
                self.verticalLayout_3.setContentsMargins(9, 50, -1, 9)
                self.verticalLayout_3.setSpacing(0)
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.label = QtWidgets.QLabel(self.frame_3)
                self.label.setText("")
                self.label.setPixmap(QtGui.QPixmap(":/img/list_992.png"))
                self.label.setAlignment(QtCore.Qt.AlignCenter)
                self.label.setObjectName("label")
                self.verticalLayout_3.addWidget(self.label)
                self.label_2 = QtWidgets.QLabel(self.frame_3)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(16)
                font.setBold(True)
                font.setWeight(75)
                self.label_2.setFont(font)
                self.label_2.setAlignment(QtCore.Qt.AlignCenter)
                self.label_2.setObjectName("label_2")
                self.verticalLayout_3.addWidget(self.label_2)
                self.verticalLayout.addWidget(self.frame_3)
                self.frame_4 = QtWidgets.QFrame(self.frame_2)
                self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_4.setObjectName("frame_4")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.label_5 = QtWidgets.QLabel(self.frame_4)
                self.label_5.setMaximumSize(QtCore.QSize(56, 16777215))
                self.label_5.setObjectName("label_5")
                self.horizontalLayout_2.addWidget(self.label_5)
                self.ID_edit = QtWidgets.QLineEdit(self.frame_4)
                self.ID_edit.setEnabled(True)
                self.ID_edit.setMaximumSize(QtCore.QSize(284, 30))
                self.ID_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                "color: rgb(0, 0, 0);")
                self.ID_edit.setDragEnabled(False)
                self.ID_edit.setReadOnly(False)
                self.ID_edit.setObjectName("ID_edit")
                self.horizontalLayout_2.addWidget(self.ID_edit)
                self.verticalLayout_2.addLayout(self.horizontalLayout_2)
                self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_3.setObjectName("horizontalLayout_3")
                self.label_3 = QtWidgets.QLabel(self.frame_4)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(8)
                self.label_3.setFont(font)
                self.label_3.setObjectName("label_3")
                self.horizontalLayout_3.addWidget(self.label_3)
                self.username_edit = QtWidgets.QLineEdit(self.frame_4)
                self.username_edit.setMaximumSize(QtCore.QSize(16777215, 30))
                self.username_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                "color: rgb(0, 0, 0);")
                self.username_edit.setObjectName("username_edit")
                self.horizontalLayout_3.addWidget(self.username_edit)
                self.verticalLayout_2.addLayout(self.horizontalLayout_3)
                self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_4.setObjectName("horizontalLayout_4")
                self.label_4 = QtWidgets.QLabel(self.frame_4)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.label_4.setFont(font)
                self.label_4.setObjectName("label_4")
                self.horizontalLayout_4.addWidget(self.label_4)
                self.password_edit = QtWidgets.QLineEdit(self.frame_4)
                self.password_edit.setMaximumSize(QtCore.QSize(16777215, 30))
                self.password_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                "color: rgb(0, 0, 0);")
                self.password_edit.setObjectName("password_edit")
                self.horizontalLayout_4.addWidget(self.password_edit)
                self.verticalLayout_2.addLayout(self.horizontalLayout_4)
                self.verticalLayout.addWidget(self.frame_4)
                self.frame_5 = QtWidgets.QFrame(self.frame_2)
                self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
                self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_5.setObjectName("frame_5")
                self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
                self.horizontalLayout_5.setObjectName("horizontalLayout_5")
                self.modify_edit = QtWidgets.QPushButton(self.frame_5)
                self.modify_edit.setMaximumSize(QtCore.QSize(100, 30))
                self.modify_edit.setStyleSheet("background-color: rgb(0, 0, 18);")
                self.modify_edit.setDefault(True)
                self.modify_edit.setObjectName("modify_edit")
                self.horizontalLayout_5.addWidget(self.modify_edit)
                self.cancel_edit = QtWidgets.QPushButton(self.frame_5)
                self.cancel_edit.setMaximumSize(QtCore.QSize(100, 30))
                self.cancel_edit.setStyleSheet("background-color: rgb(0, 0, 18);")
                self.cancel_edit.setDefault(True)
                self.cancel_edit.setFlat(False)
                self.cancel_edit.setObjectName("cancel_edit")
                self.horizontalLayout_5.addWidget(self.cancel_edit)
                self.verticalLayout.addWidget(self.frame_5)
                self.horizontalLayout_6.addWidget(self.frame_2)
                self.horizontalLayout.addWidget(self.frame)
                self.ID_edit.setDisabled(True)
                self.modify_edit.clicked.connect(self.on_edit)
                self.cancel_edit.clicked.connect(Edit.close)

                self.retranslateUi(Edit)
                QtCore.QMetaObject.connectSlotsByName(Edit)

        def retranslateUi(self, Edit):
                _translate = QtCore.QCoreApplication.translate
                Edit.setWindowTitle(_translate("Edit", "Edit"))
                self.label_2.setText(_translate("Edit", "Edit"))
                self.label_5.setText(_translate("Edit", "ID:"))
                self.label_3.setText(_translate("Edit", "Username :"))
                self.label_4.setText(_translate("Edit", "Password :"))
                self.modify_edit.setText(_translate("Edit", "Modify"))
                self.cancel_edit.setText(_translate("Edit", "Cancel"))
                
        
        def on_edit(self):
                username = self.username_edit.text()
                password = self.password_edit.text()
                id = self.ID_edit.text()
                date  = datetime.date.today().strftime('%y/%m/%d')
                cursor = QSqlQuery()
                query = "update users set username = '"+username+"', password = '"+password+"',Date = '"+date+"' where ID = '"+id+"'"
                self.signal.emit(query)
                self.edit.close()
                


import ressources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Edit = QtWidgets.QWidget()
    ui = Ui_Edit()
    ui.setupUi(Edit)
    Edit.show()
    sys.exit(app.exec_())

