# -*- coding: utf-8 -*-

# Login implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSql import QSqlDatabase , QSqlQuery
from PyQt5.QtWidgets import QMessageBox
import ressources
import os
from Navigation import Ui_navigation
from Edit import Ui_Edit

class Ui_Login(object):
        def setupUi(self, Login):
                directory = str(os.getcwd()).replace('\\','/')+"/Database/database.db"
                self.db = QSqlDatabase.addDatabase("QSQLITE")
                self.db.setDatabaseName(directory)
                Login.setObjectName("Login")
                Login.resize(455, 645)
                self.verticalLayout = QtWidgets.QVBoxLayout(Login)
                self.verticalLayout.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout.setSpacing(0)
                self.verticalLayout.setObjectName("verticalLayout")
                self.frame = QtWidgets.QFrame(Login)
                self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
                self.frame.setStyleSheet("background-color: rgb(0, 0, 8);")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
                self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_5.setSpacing(0)
                self.horizontalLayout_5.setObjectName("horizontalLayout_5")
                self.verticalLayout.addWidget(self.frame)
                self.frame_2 = QtWidgets.QFrame(Login)
                self.frame_2.setStyleSheet("background-color: rgb(0, 0, 8);")
                self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_2.setObjectName("frame_2")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
                self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout.setSpacing(0)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.frame_4 = QtWidgets.QFrame(self.frame_2)
                self.frame_4.setMaximumSize(QtCore.QSize(350, 16777215))
                self.frame_4.setStyleSheet("")
                self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_4.setObjectName("frame_4")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
                self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_2.setSpacing(0)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.frame_5 = QtWidgets.QFrame(self.frame_4)
                self.frame_5.setMaximumSize(QtCore.QSize(16777215, 200))
                self.frame_5.setStyleSheet("")
                self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_5.setObjectName("frame_5")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout()
                self.verticalLayout_3.setContentsMargins(-1, -1, -1, 6)
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.label = QtWidgets.QLabel(self.frame_5)
                self.label.setMaximumSize(QtCore.QSize(16777215, 200))
                self.label.setText("")
                self.label.setPixmap(QtGui.QPixmap(":/img/280.png"))
                self.label.setAlignment(QtCore.Qt.AlignCenter)
                self.label.setObjectName("label")
                self.verticalLayout_3.addWidget(self.label)
                self.label_2 = QtWidgets.QLabel(self.frame_5)
                font = QtGui.QFont()
                font.setPointSize(28)
                self.label_2.setFont(font)
                self.label_2.setStyleSheet("color:white;")
                self.label_2.setAlignment(QtCore.Qt.AlignCenter)
                self.label_2.setObjectName("label_2")
                self.verticalLayout_3.addWidget(self.label_2)
                self.horizontalLayout_2.addLayout(self.verticalLayout_3)
                self.verticalLayout_2.addWidget(self.frame_5)
                self.frame_6 = QtWidgets.QFrame(self.frame_4)
                self.frame_6.setMaximumSize(QtCore.QSize(16777215, 200))
                self.frame_6.setStyleSheet("")
                self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_6.setObjectName("frame_6")
                self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
                self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
                self.verticalLayout_4.setObjectName("verticalLayout_4")
                self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_3.setContentsMargins(5, -1, -1, -1)
                self.horizontalLayout_3.setSpacing(20)
                self.horizontalLayout_3.setObjectName("horizontalLayout_3")
                self.label_3 = QtWidgets.QLabel(self.frame_6)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_3.setFont(font)
                self.label_3.setStyleSheet("color:rgb(106, 106, 106);")
                self.label_3.setObjectName("label_3")
                self.horizontalLayout_3.addWidget(self.label_3)
                self.username = QtWidgets.QLineEdit(self.frame_6)
                self.username.setMaximumSize(QtCore.QSize(16777215, 30))
                self.username.setStyleSheet("QLineEdit{\n"
                "color:white;\n"
                "border-radius: 5px;\n"
                "border: 1px solid white;\n"
                "padding:5px;\n"
                "}\n"
                "QLineEdit:hover{\n"
                "color: rgb(0, 0, 106);\n"
                "border: 3px solid rgb(0, 0, 106);\n"
                "background-color:white;\n"
                "}\n"
                "QLineEdit:focus{\n"
                "color: rgb(0, 0, 106);\n"
                "border: 2px solid rgb(0, 0, 106);\n"
                "background-color:white;\n"
                "}\n"
                "\n"
                "")
                self.username.setObjectName("username")
                self.horizontalLayout_3.addWidget(self.username)
                self.verticalLayout_4.addLayout(self.horizontalLayout_3)
                self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_4.setContentsMargins(5, -1, -1, -1)
                self.horizontalLayout_4.setSpacing(20)
                self.horizontalLayout_4.setObjectName("horizontalLayout_4")
                self.label_4 = QtWidgets.QLabel(self.frame_6)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_4.setFont(font)
                self.label_4.setStyleSheet("color:rgb(106, 106, 106);")
                self.label_4.setObjectName("label_4")
                self.horizontalLayout_4.addWidget(self.label_4)
                self.password = QtWidgets.QLineEdit(self.frame_6)
                self.password.setMaximumSize(QtCore.QSize(16777215, 30))
                self.password.setStyleSheet("QLineEdit{\n"
                "color:white;\n"
                "border-radius: 5px;\n"
                "border: 1px solid white;\n"
                "}\n"
                "QLineEdit:hover{\n"
                "color :  rgb(0, 0, 106);\n"
                "border: 2px solid rgb(0, 0, 106);\n"
                "background-color:white;\n"
                "}\n"
                "QLineEdit:focus{\n"
                "color: rgb(0, 0, 106);\n"
                "border: 2px solid rgb(0, 0, 106);\n"
                "background-color:white;\n"
                "}")
                self.password.setEchoMode(QtWidgets.QLineEdit.Password)
                self.password.setObjectName("password")
                self.horizontalLayout_4.addWidget(self.password)
                self.verticalLayout_4.addLayout(self.horizontalLayout_4)
                self.verticalLayout_2.addWidget(self.frame_6)
                self.pushButton = QtWidgets.QPushButton(self.frame_4)
                self.pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
                self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.pushButton.setStyleSheet("QPushButton{\n"
                "color:white;\n"
                "background-color: rgb(106, 106, 106);\n"
                "font: 10pt \"Segoe UI\";\n"
                "}\n"
                "QPushButton:hover{\n"
                "    background-color:rgb(0, 0, 29);\n"
                "}")
                self.pushButton.setObjectName("pushButton")
                self.verticalLayout_2.addWidget(self.pushButton)
                self.horizontalLayout.addWidget(self.frame_4)
                self.verticalLayout.addWidget(self.frame_2)
                self.frame_3 = QtWidgets.QFrame(Login)
                self.frame_3.setMaximumSize(QtCore.QSize(16777215, 35))
                self.frame_3.setStyleSheet("background-color: rgb(0, 0, 8);")
                self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_3.setObjectName("frame_3")
                self.verticalLayout.addWidget(self.frame_3)
                self.pushButton.clicked.connect(self.on_authentification_clicked)

                self.retranslateUi(Login)
                QtCore.QMetaObject.connectSlotsByName(Login)

        def retranslateUi(self, Login):
                _translate = QtCore.QCoreApplication.translate
                Login.setWindowTitle(_translate("Login", "Login"))
                self.label_2.setText(_translate("Login", "Login"))
                self.label_3.setText(_translate("Login", "Username:"))
                self.label_4.setText(_translate("Login", "Password :"))
                self.pushButton.setText(_translate("Login", "Connexion"))
        
        def on_authentification_clicked(self):
                if self.db.open():
                        find = False
                        username = self.username.text()
                        password = self.password.text()
                        query = "select username,password from users"
                        cursor = QSqlQuery()
                        cursor.prepare(query)
                        if cursor.exec():
                                while cursor.next():
                                        if username != cursor.value("username") and password != cursor.value("password") :
                                                pass
                                        else :
                                                find = True
                                                break
                                if find :
                                        Login.close()
                                        self.window = QtWidgets.QWidget()
                                        self.ui = Ui_navigation()
                                        self.ui.setupUi(self.window)
                                        self.window.show()
                                else:
                                        QMessageBox().critical(Login,"Attention","Username or Password doesn't match")
                                self.username.setText("")
                                self.password.setText("")

                        else :
                                QMessageBox().critical(Login,"Database connection Error",QSqlQuery.lastError())
                else:
                        QSqlQuery.lastError()

                        

    
    
    



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
