# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Users.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSql import QSqlDatabase , QSqlQuery
import ressources
import os
import datetime
from Edit import Ui_Edit



class Ui_Users(QtWidgets.QWidget):
        def setupUi(self, Users):
                self.users = Users
                directory = str(os.getcwd()).replace('\\','/')+"/Database/database.db"
                self.db = QSqlDatabase.addDatabase("QSQLITE")
                self.db.setDatabaseName(directory)
                Users.setObjectName("Users")
                Users.resize(671, 602)
                Users.setStyleSheet("background-color: rgb(0, 0, 8);")
                self.horizontalLayout_7 = QtWidgets.QHBoxLayout(Users)
                self.horizontalLayout_7.setObjectName("horizontalLayout_7")
                self.frame = QtWidgets.QFrame(Users)
                self.frame.setMaximumSize(QtCore.QSize(700, 16777215))
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
                self.horizontalLayout_6.setObjectName("horizontalLayout_6")
                self.frame_2 = QtWidgets.QFrame(self.frame)
                self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_2.setObjectName("frame_2")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
                self.verticalLayout.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout.setSpacing(0)
                self.verticalLayout.setObjectName("verticalLayout")
                self.frame_4 = QtWidgets.QFrame(self.frame_2)
                self.frame_4.setMaximumSize(QtCore.QSize(16777215, 60))
                self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_4.setObjectName("frame_4")
                self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_4)
                self.horizontalLayout_8.setContentsMargins(0, 20, -1, 20)
                self.horizontalLayout_8.setObjectName("horizontalLayout_8")
                self.label_5 = QtWidgets.QLabel(self.frame_4)
                self.label_5.setText("")
                self.label_5.setPixmap(QtGui.QPixmap(":/img/267.png"))
                self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
                self.label_5.setObjectName("label_5")
                self.horizontalLayout_8.addWidget(self.label_5)
                self.label_4 = QtWidgets.QLabel(self.frame_4)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(16)
                font.setBold(False)
                font.setWeight(50)
                self.label_4.setFont(font)
                self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
                self.label_4.setObjectName("label_4")
                self.horizontalLayout_8.addWidget(self.label_4)
                self.verticalLayout.addWidget(self.frame_4)
                self.frame_3 = QtWidgets.QFrame(self.frame_2)
                self.frame_3.setMaximumSize(QtCore.QSize(16777215, 300))
                self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_3.setObjectName("frame_3")
                self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
                self.horizontalLayout_5.setObjectName("horizontalLayout_5")
                self.tableWidget = QtWidgets.QTableWidget(self.frame_3)
                self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.tableWidget.setObjectName("tableWidget")
                self.tableWidget.setColumnCount(6)
                self.tableWidget.setRowCount(0)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(1, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(2, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(3, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(4, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(5, item)
                self.horizontalLayout_5.addWidget(self.tableWidget)
                self.verticalLayout.addWidget(self.frame_3)
                self.frame_5 = QtWidgets.QFrame(self.frame_2)
                self.frame_5.setMaximumSize(QtCore.QSize(16777215, 300))
                self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_5.setObjectName("frame_5")
                self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
                self.verticalLayout_4.setObjectName("verticalLayout_4")
                self.frame_6 = QtWidgets.QFrame(self.frame_5)
                self.frame_6.setMaximumSize(QtCore.QSize(16777215, 30))
                self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_6.setObjectName("frame_6")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
                self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_2.setSpacing(0)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.label = QtWidgets.QLabel(self.frame_6)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(12)
                font.setBold(False)
                font.setWeight(50)
                self.label.setFont(font)
                self.label.setStyleSheet("color: rgb(255, 255, 255);")
                self.label.setObjectName("label")
                self.verticalLayout_2.addWidget(self.label)
                self.verticalLayout_4.addWidget(self.frame_6)
                self.frame_7 = QtWidgets.QFrame(self.frame_5)
                self.frame_7.setMaximumSize(QtCore.QSize(16777215, 150))
                self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_7.setObjectName("frame_7")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
                self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.frame_8 = QtWidgets.QFrame(self.frame_7)
                self.frame_8.setMaximumSize(QtCore.QSize(16777215, 150))
                self.frame_8.setStyleSheet("")
                self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_8.setObjectName("frame_8")
                self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
                self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_5.setSpacing(0)
                self.verticalLayout_5.setObjectName("verticalLayout_5")
                self.frame_10 = QtWidgets.QFrame(self.frame_8)
                self.frame_10.setMaximumSize(QtCore.QSize(400, 100))
                self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_10.setObjectName("frame_10")
                self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
                self.verticalLayout_7.setContentsMargins(0, 0, -1, -1)
                self.verticalLayout_7.setSpacing(9)
                self.verticalLayout_7.setObjectName("verticalLayout_7")
                self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_3.setObjectName("horizontalLayout_3")
                self.label_2 = QtWidgets.QLabel(self.frame_10)
                self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_2.setObjectName("label_2")
                self.horizontalLayout_3.addWidget(self.label_2)
                self.username = QtWidgets.QLineEdit(self.frame_10)
                self.username.setMaximumSize(QtCore.QSize(16777215, 25))
                self.username.setStyleSheet("QLineEdit{\n"
                        "background-color: rgb(255, 255, 255);\n"
                        "}")
                self.username.setObjectName("username")
                self.horizontalLayout_3.addWidget(self.username)
                self.verticalLayout_7.addLayout(self.horizontalLayout_3)
                self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_4.setObjectName("horizontalLayout_4")
                self.label_3 = QtWidgets.QLabel(self.frame_10)
                self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_3.setObjectName("label_3")
                self.horizontalLayout_4.addWidget(self.label_3)
                self.password = QtWidgets.QLineEdit(self.frame_10)
                self.password.setMaximumSize(QtCore.QSize(16777215, 25))
                self.password.setStyleSheet("QLineEdit{\n"
                "background-color: rgb(255, 255, 255);\n"
                "}")
                self.password.setEchoMode(QtWidgets.QLineEdit.Password)
                self.password.setObjectName("password")
                self.horizontalLayout_4.addWidget(self.password)
                self.verticalLayout_7.addLayout(self.horizontalLayout_4)
                self.verticalLayout_5.addWidget(self.frame_10)
                self.frame_11 = QtWidgets.QFrame(self.frame_8)
                self.frame_11.setMaximumSize(QtCore.QSize(150, 50))
                self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_11.setObjectName("frame_11")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_11)
                self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.add_btn = QtWidgets.QPushButton(self.frame_11)
                self.add_btn.setMaximumSize(QtCore.QSize(16777215, 40))
                self.add_btn.setStyleSheet("QPushButton{\n"
                        "color: rgb(255, 255, 255);\n"
                        "background-color: rgb(0, 0, 20);\n"
                        "}")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap(":/img/448.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.add_btn.setIcon(icon)
                self.add_btn.setAutoDefault(False)
                self.add_btn.setFlat(False)
                self.add_btn.setObjectName("add_btn")
                self.horizontalLayout_2.addWidget(self.add_btn)
                self.verticalLayout_5.addWidget(self.frame_11)
                self.horizontalLayout.addWidget(self.frame_8)
                self.frame_9 = QtWidgets.QFrame(self.frame_7)
                self.frame_9.setMaximumSize(QtCore.QSize(200, 16777215))
                self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_9.setObjectName("frame_9")
                self.horizontalLayout.addWidget(self.frame_9)
                self.verticalLayout_4.addWidget(self.frame_7)
                self.verticalLayout.addWidget(self.frame_5)
                self.horizontalLayout_6.addWidget(self.frame_2)
                self.horizontalLayout_7.addWidget(self.frame)
                self.add_btn.clicked.connect(self.Add_User)
                self.Refresh_User()

                self.retranslateUi(Users)
                QtCore.QMetaObject.connectSlotsByName(Users)

        def retranslateUi(self, Users):
                _translate = QtCore.QCoreApplication.translate
                Users.setWindowTitle(_translate("Users", "User Window"))
                self.label_4.setText(_translate("Users", "Users Window"))
                item = self.tableWidget.horizontalHeaderItem(0)
                item.setText(_translate("Users", "ID"))
                item = self.tableWidget.horizontalHeaderItem(1)
                item.setText(_translate("Users", "Username"))
                item = self.tableWidget.horizontalHeaderItem(2)
                item.setText(_translate("Users", "Password"))
                item = self.tableWidget.horizontalHeaderItem(3)
                item.setText(_translate("Users", "Date"))
                item = self.tableWidget.horizontalHeaderItem(4)
                item.setText(_translate("Users", "Action"))
                self.label.setText(_translate("Users", "Add new User"))
                self.label_2.setText(_translate("Users", "Username :"))
                self.label_3.setText(_translate("Users", "Password :"))
                self.add_btn.setText(_translate("Users", "Add"))

        def Add_User(self):
                if self.db.open():
                        username = self.username.text()
                        password = self.password.text()
                        date  = datetime.date.today().strftime('%y/%m/%d')
                        cursor = QSqlQuery()
                        query = "insert into users ('username','password','Date') values(:username,:password,:date)"
                        cursor.prepare(query)
                        cursor.bindValue(":username",username)
                        cursor.bindValue(":password",password)
                        cursor.bindValue(":date",date)
                        if cursor.exec() :
                                print("user add with success")
                                self.Refresh_User()
                        else :
                                print("failed adding user")
                else :
                        print("failed opening database")
                self.db.close()

        def Refresh_User(self):
                i = 0
                if self.db.open():
                        cursor = QSqlQuery()
                        row = int(self.get_row_count())
                        query = "select * from users"
                        cursor.prepare(query)
                        if cursor.exec() :
                                while cursor.next() :
                                        self.tableWidget.setRowCount(row)
                                        id = cursor.value("ID")
                                        username = cursor.value("username")
                                        password = cursor.value("password")
                                        date = cursor.value("date")
                                        self.delete = QtWidgets.QPushButton("x")
                                        self.edit = QtWidgets.QPushButton("+")
                                        self.edit.setStyleSheet("background-color:yellow;width:20px;height:20px;color:white;")
                                        self.delete.setStyleSheet("background-color:red;width:20px;height:20px;color:white;")
                                        self.tableWidget.setItem(i,0,QtWidgets.QTableWidgetItem(str(id)))
                                        self.tableWidget.setItem(i,1,QtWidgets.QTableWidgetItem(username))
                                        self.tableWidget.setItem(i,2,QtWidgets.QTableWidgetItem(password))
                                        self.tableWidget.setItem(i,3,QtWidgets.QTableWidgetItem(str(date)))
                                        self.tableWidget.setCellWidget(i,4,self.delete)
                                        self.tableWidget.setCellWidget(i,5,self.edit)
                                        i= i+1                        
                                        self.delete.clicked.connect(self.remove)
                                        self.edit.clicked.connect(self.on_edit)
                        else :
                                QSqlQuery.lastError()
                else :
                        print(self.db.lastError().text())
                self.db.close()

        def get_row_count(self):
                if self.db.open():
                        cursor = QSqlQuery()
                        row = "select *,count(ID) as row from users"
                        cursor.prepare(row)
                        if cursor.exec():
                                if cursor.next():
                                        return cursor.value("row")
                        else :
                                print(QSqlQuery.lastError())
                else :
                        print(QSqlQuery.lastError())
                self.db.close()
                
        def remove(self):
                row = self.tableWidget.currentRow()
                col = self.tableWidget.currentColumn()
                item = self.tableWidget.item(row,0).text()
                message_box = QtWidgets.QMessageBox()
                answer = message_box.question(self.users,"Delete","Are you sure?")
                if answer == 65536 :
                        return
                else :
                        if self.db.open():
                                cursor = QSqlQuery()
                                query = "delete from users where ID = '"+item+"'"
                                cursor.prepare(query)
                                if cursor.exec():
                                        self.Refresh_User()        

                                else :
                                        print(QSqlQuery.lastError())
                        else :
                                print(QSqlQuery.lastError())
                self.db.close()
                
        def on_edit(self):
                row = self.tableWidget.currentRow()
                col = self.tableWidget.currentColumn()
                id = self.tableWidget.item(row,0).text()
                username = self.tableWidget.item(row,1).text()
                password = self.tableWidget.item(row,2).text()
                self.db.close()
                self.window = QtWidgets.QWidget()
                self.ui = Ui_Edit()
                self.ui.setupUi(self.window)
                self.ui.password_edit.setText(password)
                self.ui.username_edit.setText(username)
                self.ui.ID_edit.setText(id)
                self.window.show()
                self.ui.signal.connect(self.refresh_edit)

        def refresh_edit(self,query):
                if self.db.open():
                        cursor = QSqlQuery()
                        cursor.prepare(query)
                        if cursor.exec() :
                                self.Refresh_User()
                        else :
                                QSqlQuery.lastError()
                else :
                        print(self.db.lastError().text())
                self.db.close()

                
               
                
                


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Users = QtWidgets.QWidget()
    ui = Ui_Users()
    ui.setupUi(Users)
    app.setStyle("Fusion")
    Users.show()
    sys.exit(app.exec_())
